export const GET_JOBS = 'GET_JOBS'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'
export const GET_JOBS_API_ERROR = 'GET_JOBS_API_ERROR'

export const CREATE_JOBS = 'CREATE_JOBS'
export const CREATE_JOBS_SUCCESS = 'CREATE_JOBS_SUCCESS'
export const CREATE_JOBS_API_ERROR = 'CREATE_JOBS_API_ERROR'